apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-gateway
  labels:
    app: agents-gateway
spec:
  selector:
    matchLabels:
      app: agents-gateway
  template:
    metadata:
      labels:
        app: agents-gateway
    spec:
      serviceAccountName: agents-gateway
      containers:
      - name: server
        image: agents-gateway
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PROJECT_ID
          value: "gemini-adk-vertex-2025"
        - name: GOOGLE_CLOUD_PROJECT
          value: "gemini-adk-vertex-2025"
        - name: REGION
          value: "europe-west1"
        - name: GOOGLE_CLOUD_LOCATION
          value: "europe-west1"
        - name: DB_HOST
          value: "34.14.6.17"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: API_TOP_K_MAX
          value: "50"
        - name: MAX_UPLOAD_MB
          value: "25"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MODERATION_THRESHOLD
          value: "0.5"
        - name: ALLOYDB_SECRET_NAME
          value: "alloydb-secret"
        - name: GOOGLE_API_KEY_SECRET_NAME
          value: "google-api-key-secret"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: agents-gateway
  labels:
    app: agents-gateway
spec:
  type: ClusterIP
  selector:
    app: agents-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agents-gateway
  annotations:
    iam.gke.io/gcp-service-account: alloydb-user-sa@gemini-adk-vertex-2025.iam.gserviceaccount.com
