apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-gateway
  labels:
    app: agents-gateway
spec:
  selector:
    matchLabels:
      app: agents-gateway
  template:
    metadata:
      labels:
        app: agents-gateway
    spec:
      serviceAccountName: agents-gateway
      containers:
      - name: server
        image: agents-gateway:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: PROJECT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REGION
          value: "europe-west1"
        - name: DB_HOST
          value: "productcatalog-alloydb"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "products"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agents-gateway-secrets
              key: DB_PASSWORD
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: agents-gateway
  labels:
    app: agents-gateway
spec:
  type: ClusterIP
  selector:
    app: agents-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8085
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agents-gateway
---
apiVersion: v1
kind: Secret
metadata:
  name: agents-gateway-secrets
type: Opaque
stringData:
  DB_PASSWORD: "change-me"


